### ISSUE TITLE
Not being able to load ib-world in the local version of ironbane

### ISSUE THREAD

**Issue by ChaiTeaNunes** [ironbane/ironbane-client#10]

**Comment by bsparks** [comment]
You need a clara.io account. You need to go into your account section and get the API key.
create a clara.json file in the root of the project, and put this information in it
the scenes are from your account (created or shared with you).

```
{
    "name": "username",
    "apiKey": "xxxxxxxxxxf",
    "sceneNamesToExport": [
        "Storage Room"
    ]
}
```

in app.js you need to load the level using snake case, for example Storage Room from above will be storage-room

you need to also run `angus buildZones` after creating this file.
