### ISSUE TITLE
Tower of Doom Spawning

### ISSUE THREAD

**Issue by ChaiTeaNunes** [ironbane/ironbane-client#15]
When you spawn in the Tower of Doom, you are inside of the wall and you fall. I managed to catch onto the floor.

![](http://i.imgur.com/Hl5UEZg.png)

**Comment by eric-ycw** [comment]
Make sure you're using the online version.

**Comment by ChaiTeaNunes** [comment]
This is not the online version but it's still a bug, right? Is this not a bug? Can we not change the spawnpoint?

**Comment by eric-ycw** [comment]
Right. I'll ask the devs about it.
